### PR TITLE
Add showdown

### PR DESCRIPTION
**Pull request by todorm85**
Add showdown functionality to TwoPlayersHandLogic. The list of player`s showdown cards is passed as property ShowdownCards of the EndHandContext object to IPlayer.EndHand() method.
Issue #15

### CODE REVIEW

**Comment by todorm85** [comment]
This can be useful if bots are looking for bluffs.

**Comment by NikolayIT** [comment]
Does this logic always show cards or does it show cards only when both players are in game (i.e. not folded already)?

**Comment by todorm85** [comment]
It shows all cards of only the players that have not folded. (IPlayer.InHand == true)

**Comment by todorm85** [comment]
Must not show player`s cards if he`s only one left in hand.

**Pull request closed without merging**
